# 매매

In [2]:
import pandas as pd
import xml.etree.ElementTree as ET
import requests
url = "http://openapi.seoul.go.kr:8088/sample/xml/tbLnOpendataRtmsV/1/5/"
response = requests.get(url)
root = ET.fromstring(response.content)
data = [
    {element.tag: element.text for element in row}
    for row in root.findall('.//row')
]
pd.DataFrame(data)

  ACC_YEAR SGG_CD SGG_NM BJDONG_CD  ... BUILD_YEAR HOUSE_TYPE REQ_GBN RDEALER_LAWDNM
0     2023  11710    송파구     10800  ...       2018       오피스텔    중개거래         서울 송파구
1     2023  11560   영등포구     10900  ...       2012       오피스텔    중개거래        서울 영등포구
2     2023  11380    은평구     10500  ...       2012      연립다세대    중개거래         서울 은평구
3     2023  11620    관악구     10100  ...       2000        아파트    중개거래         서울 관악구
4     2023  11500    강서구     10300  ...       2017      연립다세대    중개거래         서울 강서구

[5 rows x 21 columns]

# 전월세

In [5]:
import pandas as pd
import xml.etree.ElementTree as ET
import requests
url = "	http://openapi.seoul.go.kr:8088/sample/xml/tbLnOpendataRentV/1/5/"
response = requests.get(url)
root = ET.fromstring(response.content)
data = [
    {element.tag: element.text for element in row}
    for row in root.findall('.//row')
]
pd.DataFrame(data)

  ACC_YEAR SGG_CD  ... BEFORE_GRNTY_AMOUNT BEFORE_MT_RENT_CHRGE
0     2023  11410  ...                None                 None
1     2023  11215  ...                   0                    0
2     2023  11230  ...                   0                 None
3     2023  11680  ...               19800                 None
4     2023  11140  ...                5000                   45

[5 rows x 23 columns]

In [6]:
import pandas as pd
import xml.etree.ElementTree as ET
import requests

url = "http://openapi.seoul.go.kr:8088/sample/xml/tbLnOpendataRtmsV/1/5/"
response = requests.get(url)
root = ET.fromstring(response.content)

data = []
for row in root.findall('.//row'):
    row_data = {}
    for element in row:
        row_data[element.tag] = element.text
    data.append(row_data)

df = pd.DataFrame(data)
print(df)

  ACC_YEAR SGG_CD SGG_NM BJDONG_CD  ... BUILD_YEAR HOUSE_TYPE REQ_GBN RDEALER_LAWDNM
0     2023  11710    송파구     10800  ...       2018       오피스텔    중개거래         서울 송파구
1     2023  11560   영등포구     10900  ...       2012       오피스텔    중개거래        서울 영등포구
2     2023  11380    은평구     10500  ...       2012      연립다세대    중개거래         서울 은평구
3     2023  11620    관악구     10100  ...       2000        아파트    중개거래         서울 관악구
4     2023  11500    강서구     10300  ...       2017      연립다세대    중개거래         서울 강서구

[5 rows x 21 columns]

In [11]:
import requests
import pandas as pd 

serviceKey = 'FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D'
pageNo = 1 # 페이지 번호
numOfRows = 1000 # 한 페이지 결과수
LAWD_CD = 11560 # 지역코드
DEAL_YMD = 202307 # 계약월
url = f'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey={serviceKey}&pageNo={pageNo}&numOfRows=10&LAWD_CD={LAWD_CD}&DEAL_YMD={DEAL_YMD}'
req = requests.get(url)
req.text

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>99</resultCode><resultMsg>SERVICE KEY IS NOT REGISTERED ERROR.</resultMsg></header></response>'

In [7]:
http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?_wadl&type=xml

Requirement already satisfied: xmltodict in c:\users\bean\desktop\mtc_28\venv\lib\site-packages (0.13.0)

In [10]:
import xmltodict
import pandas as pd

data_dict = xmltodict.parse(req.text)
# data_dict
pd.DataFrame(data_dict['response']['body']['items']['item'])

KeyError: 'body'

## 서울 열린데이터 광장

In [8]:
import requests
import json
import pandas as pd
SERVICE_KEY = '564b7852646a686a34336f4f6c5571'
url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/1000/2023/11560'
req = requests.get(url)

content = req.json()
result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])

result

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2023,11560,영등포구,10900,영등포동8가,1,대지,0051,0001,메이준,...,8000,17.44,25.56,6.0,,,2012,오피스텔,중개거래,서울 영등포구
1,2023,11560,영등포구,13200,신길동,1,대지,4934,0000,삼성래미안,...,75000,59.33,0.00,5.0,,,2001,아파트,중개거래,서울 영등포구
2,2023,11560,영등포구,12100,문래동3가,1,대지,0013,0000,문래해태,...,68000,84.69,0.00,13.0,,,1999,아파트,중개거래,서울 영등포구
3,2023,11560,영등포구,10300,영등포동2가,1,대지,0028,0118,그린나래,...,37500,56.51,63.16,5.0,,,2014,오피스텔,중개거래,서울 영등포구
4,2023,11560,영등포구,13300,대림동,,,,,,...,77000,216.88,111.20,0.0,,,1985,단독다가구,직거래,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47650,46.02,27.22,2.0,,,2023,연립다세대,직거래,
996,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47300,46.03,27.22,2.0,,,2023,연립다세대,직거래,
997,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47950,46.03,27.22,3.0,,,2023,연립다세대,직거래,
998,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47950,46.03,27.22,4.0,,,2023,연립다세대,직거래,
999,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,49000,46.74,27.64,3.0,,,2023,연립다세대,직거래,

In [6]:
content = req.json()
result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])

result

,ACC_YEAR,SGG_CD,SGG_NM,BJDONG_CD,BJDONG_NM,LAND_GBN,LAND_GBN_NM,BONBEON,BUBEON,BLDG_NM,...,OBJ_AMT,BLDG_AREA,TOT_AREA,FLOOR,RIGHT_GBN,CNTL_YMD,BUILD_YEAR,HOUSE_TYPE,REQ_GBN,RDEALER_LAWDNM
0,2023,11560,영등포구,10900,영등포동8가,1,대지,0051,0001,메이준,...,8000,17.44,25.56,6.0,,,2012,오피스텔,중개거래,서울 영등포구
1,2023,11560,영등포구,13200,신길동,1,대지,4934,0000,삼성래미안,...,75000,59.33,0.00,5.0,,,2001,아파트,중개거래,서울 영등포구
2,2023,11560,영등포구,12100,문래동3가,1,대지,0013,0000,문래해태,...,68000,84.69,0.00,13.0,,,1999,아파트,중개거래,서울 영등포구
3,2023,11560,영등포구,10300,영등포동2가,1,대지,0028,0118,그린나래,...,37500,56.51,63.16,5.0,,,2014,오피스텔,중개거래,서울 영등포구
4,2023,11560,영등포구,13300,대림동,,,,,,...,77000,216.88,111.20,0.0,,,1985,단독다가구,직거래,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47650,46.02,27.22,2.0,,,2023,연립다세대,직거래,
996,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47300,46.03,27.22,2.0,,,2023,연립다세대,직거래,
997,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47950,46.03,27.22,3.0,,,2023,연립다세대,직거래,
998,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,47950,46.03,27.22,4.0,,,2023,연립다세대,직거래,
999,2023,11560,영등포구,13000,양평동6가,1,대지,0075,0012,선유도윤영빌B동,...,49000,46.74,27.64,3.0,,,2023,연립다세대,직거래,

In [8]:
import requests
import json
import pandas as pd

SERVICE_KEY = '564b7852646a686a34336f4f6c5571'
base_url = 'http://openapi.seoul.go.kr:8088/'

# 각 데이터프레임의 크기
chunk_size = 1000

# 전체 데이터를 가져올 범위 설정
start_index = 1
end_index = 12000

# 데이터를 저장할 리스트 초기화
dataframes = []

# 시작 인덱스부터 끝 인덱스까지 데이터를 가져와서 리스트에 추가
for i in range(start_index, end_index + 1, chunk_size):
    # 요청할 URL 생성
    url = f'{base_url}{SERVICE_KEY}/json/tbLnOpendataRtmsV/{i}/{i + chunk_size - 1}/2023/11560'
    req = requests.get(url)
    
    # JSON 데이터 추출
    content = req.json()
    
    # 결과가 있는 경우 데이터프레임 생성 및 리스트에 추가
    if 'tbLnOpendataRtmsV' in content:
        result = pd.DataFrame(content['tbLnOpendataRtmsV']['row'])
        dataframes.append(result)

# 모든 데이터프레임을 하나로 합치기
final_df = pd.concat(dataframes, ignore_index=True)

# 결과 확인
print(final_df)

     ACC_YEAR SGG_CD SGG_NM BJDONG_CD BJDONG_NM LAND_GBN LAND_GBN_NM BONBEON  \
0        2023  11560   영등포구     10900    영등포동8가        1          대지    0051
1        2023  11560   영등포구     13200       신길동        1          대지    4934
2        2023  11560   영등포구     12100     문래동3가        1          대지    0013
3        2023  11560   영등포구     10300    영등포동2가        1          대지    0028
4        2023  11560   영등포구     13300       대림동
...       ...    ...    ...       ...       ...      ...         ...     ...
1857     2023  11560   영등포구     11800       도림동
1858     2023  11560   영등포구     13000     양평동6가        1          대지    0081
1859     2023  11560   영등포구     10800    영등포동7가        1          대지    0104
1860     2023  11560   영등포구     13300       대림동        1          대지    0851
1861     2023  11560   영등포구     10800    영등포동7가        1          대지    0208

     BUBEON         BLDG_NM  ... OBJ_AMT BLDG_AREA  TOT_AREA  FLOOR  \
0      0001             메이준  ...    8000     17.44     25.56    6.0
1      0000           삼성래미안  ...   75000     59.33      0.00    5.0
2      0000            문래해태  ...   68000     84.69      0.00   13.0
3      0118            그린나래  ...   37500     56.51     63.16    5.0
4                            ...   77000    216.88    111.20    0.0
...     ...             ...  ...     ...       ...       ...    ...
1857                         ...   66000     98.25     76.00    0.0
1858   0000          금강노블레스  ...   44000     35.54     45.12   14.0
1859   0005  여의도 웨스턴 힐 오피스텔  ...   26616     17.38     26.11    3.0
1860   0100          하나세인스톤  ...   26000     29.20     13.93    4.0
1861   0000     포레나 영등포 센트럴  ...   20600     19.31     35.15   21.0

      RIGHT_GBN  CNTL_YMD BUILD_YEAR HOUSE_TYPE REQ_GBN RDEALER_LAWDNM
0                               2012       오피스텔    중개거래        서울 영등포구
1                               2001        아파트    중개거래        서울 영등포구
2                               1999        아파트    중개거래        서울 영등포구
3                               2014       오피스텔    중개거래        서울 영등포구
4                               1985      단독다가구     직거래
...         ...       ...        ...        ...     ...            ...
1857                            1994      단독다가구    중개거래        서울 영등포구
1858             20230201       2022       오피스텔     직거래
1859                            2022       오피스텔     직거래
1860                            2016      연립다세대    중개거래        서울 영등포구
1861             20230130       2020       오피스텔    중개거래        서울 영등포구

[1862 rows x 21 columns]

In [29]:
import requests
import json
import pandas as pd
SERVICE_KEY = '564b7852646a686a34336f4f6c5571'
'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1/1000/2023/11560'
'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/1001/2000/2023/11560'

data = None
for j in range(1,13):
    url = f'http://openapi.seoul.go.kr:8088/{SERVICE_KEY}/json/tbLnOpendataRtmsV/{1+((j-1)*1000)}/{j*1000}'
    # url = f'http://openapi.seoul.go.kr:8088/{service_key}/json/tbLnOpendataRentV/1/1000/2023/11560'
    print(url)
    req = requests.get(url)
    content = req.json()
    con = content['tbLnOpendataRtmsV']['row']
    result = pd.DataFrame(con)
    data = pd.concat([data, result])
data = data.reset_index(drop=True)
data.head()

http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/1/1000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/1001/2000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/2001/3000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/3001/4000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/4001/5000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/5001/6000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/6001/7000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/7001/8000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/8001/9000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/9001/10000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/10001/11000
http://openapi.seoul.go.kr:8088/564b7852646a686a34336f4f6c5571/json/tbLnOpendataRtmsV/11001/12000

  ACC_YEAR SGG_CD SGG_NM BJDONG_CD  ... BUILD_YEAR HOUSE_TYPE REQ_GBN RDEALER_LAWDNM
0     2023  11710    송파구     10800  ...       2018       오피스텔    중개거래         서울 송파구
1     2023  11560   영등포구     10900  ...       2012       오피스텔    중개거래        서울 영등포구
2     2023  11380    은평구     10500  ...       2012      연립다세대    중개거래         서울 은평구
3     2023  11620    관악구     10100  ...       2000        아파트    중개거래         서울 관악구
4     2023  11500    강서구     10300  ...       2017      연립다세대    중개거래         서울 강서구

[5 rows x 21 columns]

In [30]:
data.to_csv("result.csv")

In [ ]:
FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D

f'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev?serviceKey={serviceKey}&pageNo={pageNo}&numOfRows=10&LAWD_CD={LAWD_CD}&DEAL_YMD={DEAL_YMD}'

In [14]:
import requests
import pandas as pd 

serviceKey = 'FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D'

url = f'http://openapi.tour.go.kr/openapi/service/TourismAccdtService/getTourismTotqyList'
req = requests.get(url)
req.text

'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><responseTime>2023-08-07T17:42:59.557+09:00</responseTime><resultCode>10</resultCode><resultMsg>INVALID REQUEST PARAMETER ERROR.</resultMsg></header></response>'

In [5]:
import pandas as pd
import requests

# 특정 인증서 파일을 사용하여 SSL 인증서 검증
response = requests.get(url, verify='/path/to/ca-cert.pem')

url = 'http://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson?serviceKey=FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D&pageNo=1&numOfRows=1000&startCreateDt=20210101'



# API 인증키
SERVICE_KEY = 'FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D'

# 요청할 URL 생성 함수
def generate_url(page_no):
    base_url = 'https://openapi.data.go.kr/openapi/service/rest/Covid19/getCovid19SidoInfStateJson'
    return f'{base_url}?serviceKey={SERVICE_KEY}&pageNo={page_no}&numOfRows=1000&startCreateDt=20210101'

# 데이터 수집 및 저장
all_data = []
page_no = 1

while True:
    url = generate_url(page_no)
    response = requests.get(url)
    data = response.json()
    items = data['response']['body']['items']
    
    if not items:  # 데이터가 없으면 종료
        break
    
    all_data.extend(items)
    print(f'Page {page_no}: Fetched {len(items)} items')
    
    page_no += 1

# 데이터프레임으로 변환하여 CSV 파일로 저장
df = pd.DataFrame(all_data)
df.to_csv('result.csv', index=False)

print('Data collected and saved to result.csv')

OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /path/to/ca-cert.pem

In [12]:
import requests

url = 'http://openapi.molit.go.kr/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTradeDev'
params ={'serviceKey' : 'FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D', 'pageNo' : '1', 'numOfRows' : '10', 'LAWD_CD' : '11110', 'DEAL_YMD' : '201512' }

response = requests.get(url, params=params)
print(response.content)

b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><resultCode>99</resultCode><resultMsg>SERVICE KEY IS NOT REGISTERED ERROR.</resultMsg></header></response>'

In [13]:
import requests

url = 'http://openapi.seoul.go.kr:8088/sample/xml/CardSubwayStatsNew/1/5/20220301'

response = requests.get(url)
print(response.content)

b'<?xml version="1.0" encoding="UTF-8"?>\n<CardSubwayStatsNew>\n<list_total_count>593</list_total_count>\n<RESULT>\n<CODE>INFO-000</CODE>\n<MESSAGE>\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4</MESSAGE>\n</RESULT>\n<row>\n<USE_DT>20220301</USE_DT>\n<LINE_NUM>1\xed\x98\xb8\xec\x84\xa0</LINE_NUM>\n<SUB_STA_NM>\xec\x84\x9c\xec\x9a\xb8\xec\x97\xad</SUB_STA_NM>\n<RIDE_PASGR_NUM>20994</RIDE_PASGR_NUM>\n<ALIGHT_PASGR_NUM>19468</ALIGHT_PASGR_NUM>\n<WORK_DT>20220304</WORK_DT>\n</row>\n<row>\n<USE_DT>20220301</USE_DT>\n<LINE_NUM>1\xed\x98\xb8\xec\x84\xa0</LINE_NUM>\n<SUB_STA_NM>\xec\x8b\x9c\xec\xb2\xad</SUB_STA_NM>\n<RIDE_PASGR_NUM>12439</RIDE_PASGR_NUM>\n<ALIGHT_PASGR_NUM>12379</ALIGHT_PASGR_NUM>\n<WORK_DT>20220304</WORK_DT>\n</row>\n<row>\n<USE_DT>20220301</USE_DT>\n<LINE_NUM>1\xed\x98\xb8\xec\x84\xa0</LINE_NUM>\n<SUB_STA_NM>\xec\xa2\x85\xea\xb0\x81</SUB_STA_NM>\n<RIDE_PASGR_NUM>15750</RIDE_PASGR_NUM>\n<ALIGHT_PASGR_NUM>13544</ALIGHT_PASGR_NUM>\n<WORK_DT>20220304</WORK_DT>\n</row>\n<row>\n<USE_DT>20220301</USE_DT>\n<LINE_NUM>1\xed\x98\xb8\xec\x84\xa0</LINE_NUM>\n<SUB_STA_NM>\xec\xa2\x85\xeb\xa1\x9c3\xea\xb0\x80</SUB_STA_NM>\n<RIDE_PASGR_NUM>16349</RIDE_PASGR_NUM>\n<ALIGHT_PASGR_NUM>14533</ALIGHT_PASGR_NUM>\n<WORK_DT>20220304</WORK_DT>\n</row>\n<row>\n<USE_DT>20220301</USE_DT>\n<LINE_NUM>1\xed\x98\xb8\xec\x84\xa0</LINE_NUM>\n<SUB_STA_NM>\xec\xa2\x85\xeb\xa1\x9c5\xea\xb0\x80</SUB_STA_NM>\n<RIDE_PASGR_NUM>14036</RIDE_PASGR_NUM>\n<ALIGHT_PASGR_NUM>13472</ALIGHT_PASGR_NUM>\n<WORK_DT>20220304</WORK_DT>\n</row>\n</CardSubwayStatsNew>\n'

In [15]:
import requests

serviceKey = 'FPSnL7hBknn%2B4ogFEqKq20afCM0Q6EcTRjCefdwtGKJa3qF8IG8NJMab9H6RZvUCyynUp6%2BjdEzpImofdHX9zA%3D%3D'

url = f'http://openapi.tour.go.kr/openapi/service/TourismAccdtService/getTourismTotqyList'
params = {
    'serviceKey': serviceKey,
    # 여기에 다른 필요한 파라미터를 추가해주세요.
}

req = requests.get(url, params=params)
print(req.text)

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><response><header><responseTime>2023-08-07T17:44:44.793+09:00</responseTime><resultCode>30</resultCode><resultMsg>SERVICE KEY IS NOT REGISTERED ERROR.</resultMsg></header></response>